PG Lab 1- Session 2 - NumPy

In [ ]:
import numpy
numpy.__version__

'1.19.5'

In [ ]:
list1=[]
list1

[]

In [ ]:
type(list1)

list

In [ ]:
list2=list(range(10))
list2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
list3=[str(c)for c in list2]
list3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [ ]:
list4=[1,1.0,'c','vivek',True]
list4


[1, 1.0, 'c', 'vivek', True]

In [ ]:
type(list4)


list

In [ ]:
# display data type of each element
[type(item)for item in list4]

[int, float, str, str, bool]

In [ ]:
#python array
import array as ar 
L= list(range(10))
A= ar.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#numpyArray
import numpy as np
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
#automatic conversion /implict of value /element
np.array([10.1,3,5,4])

array([10.1,  3. ,  5. ,  4. ])

In [ ]:
#explicit coversion/
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
#[[,,],[,,],[,,]]
#insted list result in multi-dimenstional arrays
np.array([range(i,i+3)for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
#creat a length=10 integer array filled with zero
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#creat a arrays of zeros of float type
np.zeros((2,5),dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#creat a array of ones of float type
np.ones((2,5),dtype=float) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#creat a 3x5 array filled with 3.0
np.full((3,5),3.0)

array([[3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3.]])

In [ ]:
#creat a array filled with a linear sequence
#starting at 0, ending at 20, stepping by 2
# (this is similarr to the built-in range() function)


np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
#0 to 2 4 element
#creat of an array  of evenly spaced values for the given range
np.linspace(0,2,4)

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [ ]:

#creat a 3x3 array of uniformly distributed
#random value between  0 and 1
np.random.normal((3,4))

array([[0.8039636 , 0.4490041 , 0.17665263, 0.8193335 ],
       [0.85683291, 0.73919924, 0.60546061, 0.60543353],
       [0.93734932, 0.70032474, 0.83855049, 0.07054732]])

In [ ]:
#creat a 3x3 array of random integer in the interval (0,10)

np.random.randint(0, 10, (3, 3))

array([[2, 3, 7],
       [9, 2, 5],
       [4, 5, 9]])

In [ ]:
#creat a 3x3 identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#creat an uninstallized array of three integers
#the value will we whatever happens to already exstist at that memory location

np.empty(3)

array([1., 1., 1.])

In [ ]:
import numpy as np
np.random.seed(40)# seed of reproducibilty

x1 = np.random.randint(10, size=6) # one dimenstional array
x1

array([6, 7, 5, 8, 8, 2])

In [ ]:
#seed 100 200 


np.random.seed(100)
x2=np.random.randint(200, size=(5,4,3,2,1))
x2


array([[[[[  8],
          [ 24]],

         [[ 67],
          [103]],

         [[ 87],
          [ 79]]],


        [[[176],
          [138]],

         [[ 94],
          [180]],

         [[ 98],
          [ 53]]],


        [[[ 66],
          [ 14]],

         [[ 34],
          [ 24]],

         [[143],
          [107]]],


        [[[ 60],
          [ 58]],

         [[144],
          [137]],

         [[ 93],
          [ 86]]]],



       [[[[130],
          [155]],

         [[108],
          [132]],

         [[159],
          [129]]],


        [[[141],
          [100]],

         [[  4],
          [ 91]],

         [[187],
          [ 67]]],


        [[[135],
          [ 49]],

         [[175],
          [193]],

         [[ 61],
          [ 14]]],


        [[[183],
          [199]],

         [[ 80],
          [  2]],

         [[121],
          [105]]]],



       [[[[147],
          [ 63]],

         [[181],
          [ 27]],

         [[ 56],
          [113]]],


      

In [ ]:
x2.shape

(5, 4, 3, 2, 1)

In [ ]:
x2.ndim

5

In [ ]:
x2.size

120

In [ ]:
x2.nbytes

960

In [ ]:
x2.itemsize

8